package skillregistry

import (
	"bytes"
	"context"
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Versioned view. AGENTS.md and the Engram mirror are shared between clones,
// so they must only list skills every clone can resolve: a SKILL.md inside the
// workspace that git does not ignore. Machine-local copies (a gitignored
// `.claude/skills` generated by setup, $HOME skills) stay in
// .atl/skill-registry.md, which is the local, per-machine index.

// gitCheckIgnoreTimeout bounds the single git invocation of a regeneration so a
// stuck git (network filesystem, credential helper) can never hang a startup
// hook. Hitting it is a plain git failure and falls back to "no git filtering".
const gitCheckIgnoreTimeout = 5 * time.Second

// runGitCheckIgnore is the seam over the git binary. It runs
// `git -C cwd check-ignore -z --stdin` with stdin and returns git's stdout and
// exit code. A non-nil error means git could not be run to completion (missing
// binary, timeout, I/O failure); an exit code is data, not an error. It is a
// package-level var so tests can simulate any git failure.
var runGitCheckIgnore = execGitCheckIgnore

func execGitCheckIgnore(cwd string, stdin []byte) (stdout []byte, exitCode int, err error) {
	ctx, cancel := context.WithTimeout(context.Background(), gitCheckIgnoreTimeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, "git", "-C", cwd, "check-ignore", "-z", "--stdin")
	cmd.Stdin = bytes.NewReader(stdin)
	out, runErr := cmd.Output()
	if ctx.Err() != nil {
		// A killed git reports an arbitrary exit code (1 on Windows), which must
		// never be read as "nothing is ignored".
		return nil, -1, ctx.Err()
	}
	if runErr == nil {
		return out, 0, nil
	}
	var exitErr *exec.ExitError
	if errors.As(runErr, &exitErr) {
		return out, exitErr.ExitCode(), nil
	}
	return nil, -1, runErr
}

// versionableFiles returns the set of skill files that belong in the versioned
// view: inside cwd and not ignored by git. Entries outside cwd ($HOME, absolute
// roots, `../`) are never versionable. Ignored is decided WITHOUT --no-index, so
// a tracked file under an ignored directory still counts as versioned.
//
// It runs git at most once. When git cannot give an answer (missing binary, not
// a repository, error, timeout) there is no git filtering: every file inside
// cwd counts as versionable. Git failure is never fatal.
func versionableFiles(cwd string, files []string) map[string]bool {
	type candidate struct{ file, visible string }
	var candidates []candidate
	seen := map[string]bool{}
	var visiblePaths []string
	for _, file := range files {
		if ScopeForPath(cwd, file) != "project" {
			continue
		}
		rel, err := filepath.Rel(cwd, file)
		if err != nil {
			continue
		}
		visible := gitVisiblePath(cwd, rel)
		candidates = append(candidates, candidate{file: file, visible: visible})
		if !seen[visible] {
			seen[visible] = true
			visiblePaths = append(visiblePaths, visible)
		}
	}

	versionable := make(map[string]bool, len(candidates))
	if len(candidates) == 0 {
		return versionable
	}
	// Without a git answer ignored is nil, and a nil map reads as "none ignored".
	ignored, _ := gitIgnoredPaths(cwd, visiblePaths)
	for _, c := range candidates {
		if !ignored[c.visible] {
			versionable[c.file] = true
		}
	}
	return versionable
}

// gitVisiblePath returns the cwd-relative, slash-separated path that git can
// classify for a skill file. Git refuses to check anything below a symbolic link
// ("beyond a symbolic link") and fails the whole invocation, so a symlinked
// skill directory (dotfiles/nix setups, which findAllSkillFiles deliberately
// follows) is classified by the symlink entry itself, which is what git versions.
func gitVisiblePath(cwd, rel string) string {
	parts := strings.Split(rel, string(os.PathSeparator))
	current := cwd
	for i, part := range parts {
		current = filepath.Join(current, part)
		if info, err := os.Lstat(current); err == nil && info.Mode()&os.ModeSymlink != 0 {
			return strings.Join(parts[:i+1], "/")
		}
	}
	return filepath.ToSlash(rel)
}

// gitIgnoredPaths runs the single git invocation for paths (cwd-relative,
// slash-separated) and returns the ignored subset. ok is false when git gave no
// usable answer. Exit 0 means some paths are ignored, exit 1 means none are;
// anything else (128: not a repository, other errors) is "no answer".
func gitIgnoredPaths(cwd string, paths []string) (ignored map[string]bool, ok bool) {
	var stdin bytes.Buffer
	for _, path := range paths {
		stdin.WriteString(path)
		stdin.WriteByte(0)
	}
	stdout, exitCode, err := runGitCheckIgnore(cwd, stdin.Bytes())
	if err != nil {
		return nil, false
	}
	switch exitCode {
	case 1:
		return map[string]bool{}, true
	case 0:
		ignored = map[string]bool{}
		for _, path := range strings.Split(string(stdout), "\x00") {
			if path != "" {
				ignored[path] = true
			}
		}
		return ignored, true
	default:
		return nil, false
	}
}

// filterVersionable keeps the entries whose SKILL.md is in the versionable set.
// It runs BEFORE dedupeBySkillName so that, when a name exists both as a
// versioned copy and as a local one, the versioned copy is the one listed.
func filterVersionable(entries []SkillEntry, versionable map[string]bool) []SkillEntry {
	out := make([]SkillEntry, 0, len(entries))
	for _, entry := range entries {
		if versionable[entry.Path] {
			out = append(out, entry)
		}
	}
	return out
}

// versionedFingerprint extends the scan fingerprint with the versionable set, so
// the cache invalidates when git's verdict changes (for example an edited
// .gitignore) even though no SKILL.md changed. Fingerprint itself is untouched.
func versionedFingerprint(scan string, versionable map[string]bool) string {
	paths := make([]string, 0, len(versionable))
	for path := range versionable {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	sum := sha1.Sum([]byte(scan + "\nversionable:\n" + strings.Join(paths, "\n")))
	return hex.EncodeToString(sum[:])
}
