package skillregistry

import (
	"bytes"
	"context"
	"crypto/sha1"
	"encoding/hex"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Versioned view. AGENTS.md and the Engram mirror are shared between clones,
// so they must only list skills every clone can resolve: a SKILL.md inside the
// workspace that git does not ignore. Machine-local copies (a gitignored
// `.claude/skills` generated by setup, $HOME skills) stay in
// .atl/skill-registry.md, which is the local, per-machine index.

// gitCheckIgnoreTimeout bounds the single git invocation of a regeneration so a
// stuck git (network filesystem, credential helper) can never hang a startup
// hook. Hitting it is a plain git failure and falls back to "no git filtering".
const gitCheckIgnoreTimeout = 5 * time.Second

// gitCheckIgnoreWaitDelay is how long Output may keep waiting for git's pipes
// after the timeout fired. The context only kills the process it started; on
// Windows `git.exe` in `cmd\` is a launcher that spawns `mingw64\bin\git.exe`,
// so killing the launcher leaves the real git holding stdout open and Output
// would block until that child ends, defeating the timeout.
const gitCheckIgnoreWaitDelay = time.Second

// gitRepositoryLocationVars are the variables that make git ignore the -C
// directory and answer for some other repository, index or work tree. They are
// inherited from whatever launched axiom (a git hook, a wrapper, an IDE) and
// must not decide where the ignore rules come from. GIT_CONFIG_* is kept on
// purpose: user and system ignore configuration is legitimate input.
var gitRepositoryLocationVars = map[string]bool{
	"GIT_ALTERNATE_OBJECT_DIRECTORIES": true,
	"GIT_CEILING_DIRECTORIES":          true,
	"GIT_COMMON_DIR":                   true,
	"GIT_DIR":                          true,
	"GIT_DISCOVERY_ACROSS_FILESYSTEM":  true,
	"GIT_GLOB_PATHSPECS":               true,
	"GIT_ICASE_PATHSPECS":              true,
	"GIT_IMPLICIT_WORK_TREE":           true,
	"GIT_INDEX_FILE":                   true,
	"GIT_INTERNAL_SUPER_PREFIX":        true,
	"GIT_LITERAL_PATHSPECS":            true,
	"GIT_NAMESPACE":                    true,
	"GIT_NOGLOB_PATHSPECS":             true,
	"GIT_OBJECT_DIRECTORY":             true,
	"GIT_PREFIX":                       true,
	"GIT_QUARANTINE_PATH":              true,
	"GIT_WORK_TREE":                    true,
}

// gitCheckIgnoreEnvironment returns environment (os.Environ form) without the
// repository-location variables. Names compare case-insensitively because
// Windows environment names are.
func gitCheckIgnoreEnvironment(environment []string) []string {
	out := make([]string, 0, len(environment))
	for _, entry := range environment {
		name, _, _ := strings.Cut(entry, "=")
		if gitRepositoryLocationVars[strings.ToUpper(name)] {
			continue
		}
		out = append(out, entry)
	}
	return out
}

// gitCheckIgnoreCommand builds the git invocation: bounded by ctx plus
// WaitDelay, and isolated from inherited repository-location variables.
func gitCheckIgnoreCommand(ctx context.Context, cwd string, stdin []byte) *exec.Cmd {
	cmd := exec.CommandContext(ctx, "git", "-C", cwd, "check-ignore", "-z", "--stdin")
	cmd.Stdin = bytes.NewReader(stdin)
	cmd.Env = gitCheckIgnoreEnvironment(os.Environ())
	cmd.WaitDelay = gitCheckIgnoreWaitDelay
	return cmd
}

// runGitCheckIgnore is the seam over the git binary. It runs
// `git -C cwd check-ignore -z --stdin` with stdin and returns git's stdout and
// exit code. A non-nil error means git could not be run to completion (missing
// binary, timeout, I/O failure); an exit code is data, not an error. It is a
// package-level var so tests can simulate any git failure.
var runGitCheckIgnore = execGitCheckIgnore

func execGitCheckIgnore(cwd string, stdin []byte) (stdout []byte, exitCode int, err error) {
	ctx, cancel := context.WithTimeout(context.Background(), gitCheckIgnoreTimeout)
	defer cancel()
	out, runErr := gitCheckIgnoreCommand(ctx, cwd, stdin).Output()
	if ctx.Err() != nil {
		// A killed git reports an arbitrary exit code (1 on Windows), which must
		// never be read as "nothing is ignored".
		return nil, -1, ctx.Err()
	}
	if runErr == nil {
		return out, 0, nil
	}
	var exitErr *exec.ExitError
	if errors.As(runErr, &exitErr) {
		return out, exitErr.ExitCode(), nil
	}
	return nil, -1, runErr
}

// versionableFiles returns the set of skill files that belong in the versioned
// view: inside cwd and not ignored by git. Entries outside cwd ($HOME, absolute
// roots, `../`) are never versionable. Ignored is decided WITHOUT --no-index, so
// a tracked file under an ignored directory still counts as versioned.
//
// It runs git at most once. When git cannot give an answer (missing binary, not
// a repository, error, timeout) there is no git filtering: every file inside
// cwd counts as versionable. Git failure is never fatal.
func versionableFiles(cwd string, files []string) map[string]bool {
	type candidate struct{ file, visible string }
	var candidates []candidate
	seen := map[string]bool{}
	var visiblePaths []string
	for _, file := range files {
		// One rule decides both membership and the relative path handed to git, so
		// a spelling of cwd that differs from the discovered path (Windows case or
		// 8.3 short names) can never produce a `..`-prefixed lookup.
		rel, inside := projectRelativePath(cwd, file)
		if !inside {
			continue
		}
		visible := gitVisiblePath(cwd, rel)
		candidates = append(candidates, candidate{file: file, visible: visible})
		if !seen[visible] {
			seen[visible] = true
			visiblePaths = append(visiblePaths, visible)
		}
	}

	versionable := make(map[string]bool, len(candidates))
	if len(candidates) == 0 {
		return versionable
	}
	// Without a git answer ignored is nil, and a nil map reads as "none ignored".
	ignored, _ := gitIgnoredPaths(cwd, visiblePaths)
	for _, c := range candidates {
		if !ignored[c.visible] {
			versionable[c.file] = true
		}
	}
	return versionable
}

// gitVisiblePath returns the cwd-relative, slash-separated path that git can
// classify for a skill file. Git refuses to check anything below a symbolic link
// ("beyond a symbolic link") or inside a submodule ("is in submodule") and fails
// the whole invocation, which would turn the filter off for every entry. So the
// path is cut at the first ancestor below cwd that is a symlink (dotfiles/nix
// setups, which findAllSkillFiles deliberately follows) or that owns a `.git`
// entry (a file for a submodule gitlink, a directory for a nested repository);
// that entry is what the parent repository versions or ignores.
func gitVisiblePath(cwd, rel string) string {
	parts := strings.Split(rel, string(os.PathSeparator))
	current := cwd
	for i, part := range parts {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if err != nil {
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 || (info.IsDir() && ownsGitEntry(current)) {
			return strings.Join(parts[:i+1], "/")
		}
	}
	return filepath.ToSlash(rel)
}

// ownsGitEntry reports whether dir contains a `.git` file or directory.
func ownsGitEntry(dir string) bool {
	_, err := os.Lstat(filepath.Join(dir, ".git"))
	return err == nil
}

// gitIgnoredPaths runs the single git invocation for paths (cwd-relative,
// slash-separated) and returns the ignored subset. ok is false when git gave no
// usable answer. Exit 0 means some paths are ignored, exit 1 means none are;
// anything else (128: not a repository, other errors) is "no answer".
func gitIgnoredPaths(cwd string, paths []string) (ignored map[string]bool, ok bool) {
	var stdin bytes.Buffer
	for _, path := range paths {
		stdin.WriteString(path)
		stdin.WriteByte(0)
	}
	stdout, exitCode, err := runGitCheckIgnore(cwd, stdin.Bytes())
	if err != nil {
		return nil, false
	}
	switch exitCode {
	case 1:
		return map[string]bool{}, true
	case 0:
		ignored = map[string]bool{}
		for _, path := range strings.Split(string(stdout), "\x00") {
			if path != "" {
				ignored[path] = true
			}
		}
		return ignored, true
	default:
		return nil, false
	}
}

// filterVersionable keeps the entries whose SKILL.md is in the versionable set.
// It runs BEFORE dedupeBySkillName so that, when a name exists both as a
// versioned copy and as a local one, the versioned copy is the one listed.
func filterVersionable(entries []SkillEntry, versionable map[string]bool) []SkillEntry {
	out := make([]SkillEntry, 0, len(entries))
	for _, entry := range entries {
		if versionable[entry.Path] {
			out = append(out, entry)
		}
	}
	return out
}

// versionedFingerprint extends the scan fingerprint with the versionable set, so
// the cache invalidates when git's verdict changes (for example an edited
// .gitignore) even though no SKILL.md changed. Fingerprint itself is untouched.
func versionedFingerprint(scan string, versionable map[string]bool) string {
	paths := make([]string, 0, len(versionable))
	for path := range versionable {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	sum := sha1.Sum([]byte(scan + "\nversionable:\n" + strings.Join(paths, "\n")))
	return hex.EncodeToString(sum[:])
}
